[tool.poetry]
name = "mkdocs-book"
version = "0.1.0"
description = "Built with Mkdocs"
authors = ["Francisco Alfaro <francisco.alfaro.496@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jupyterlab = "*"
jupyter-book = "*"
pre-commit = "*"
